apiVersion: v1
kind: Pod

metadata:
  name: todoapp-pod
  namespace: todoapp
  labels:
    app: todoapp

spec:
  containers:
    - name: todoapp
      image: petliuk/todoapp:3.0.0

      ports:
        - containerPort: 8000

      readinessProbe:
        httpGet:
          path: /readiness
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5

      livenessProbe:
        httpGet:
          path: /liveness
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 10